language: node_js
node_js:
 - "node"
cache:
  directories:
    - "node_modules"
before_deploy: "echo 'ready?'"
deploy:
  provider: npm
  email: "1421752582@qq.com"
  api_key: "6074ecce-c5fb-489c-9e82-8322973d31ae"