sudo: false
dist: trusty

language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_deploy: "echo 'ready?'"
deploy:
  provider: npm
  email: "1421752582@qq.com"
  api_key: "01f3cd19-07d4-4efd-acfa-5d13a367d9fb"
  on:
      tags: true
      branch: master

